//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 07:26:16 PM CDT 
//


package svc.data.citations.datasources.rejis.org.datacontract.schemas._2004._07.rejis_services_court;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CaseIndex complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CaseIndex"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AgcyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AgcyOri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BalDue" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="CaseNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CaseStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CaseStatusDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ChrgCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ChrgDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CourtName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeftName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Dob" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="IsAgcyPlus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NextDktCrtRoom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NextDktDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="PbmStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PymtUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RecId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="TktNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ViolDttm" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaseIndex", propOrder = {
    "agcyId",
    "agcyOri",
    "balDue",
    "caseNum",
    "caseStatus",
    "caseStatusDesc",
    "chrgCode",
    "chrgDesc",
    "courtName",
    "deftName",
    "dob",
    "isAgcyPlus",
    "lastName",
    "nextDktCrtRoom",
    "nextDktDate",
    "pbmStatus",
    "pymtUrl",
    "recId",
    "tktNum",
    "violDttm"
})
public class CaseIndex {

    @XmlElementRef(name = "AgcyId", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> agcyId;
    @XmlElementRef(name = "AgcyOri", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> agcyOri;
    @XmlElementRef(name = "BalDue", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> balDue;
    @XmlElementRef(name = "CaseNum", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> caseNum;
    @XmlElementRef(name = "CaseStatus", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> caseStatus;
    @XmlElementRef(name = "CaseStatusDesc", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> caseStatusDesc;
    @XmlElementRef(name = "ChrgCode", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> chrgCode;
    @XmlElementRef(name = "ChrgDesc", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> chrgDesc;
    @XmlElementRef(name = "CourtName", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> courtName;
    @XmlElementRef(name = "DeftName", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> deftName;
    @XmlElement(name = "Dob")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dob;
    @XmlElement(name = "IsAgcyPlus")
    protected Boolean isAgcyPlus;
    @XmlElementRef(name = "LastName", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lastName;
    @XmlElementRef(name = "NextDktCrtRoom", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> nextDktCrtRoom;
    @XmlElement(name = "NextDktDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar nextDktDate;
    @XmlElementRef(name = "PbmStatus", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> pbmStatus;
    @XmlElementRef(name = "PymtUrl", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> pymtUrl;
    @XmlElement(name = "RecId")
    protected Integer recId;
    @XmlElementRef(name = "TktNum", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tktNum;
    @XmlElement(name = "ViolDttm")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar violDttm;

    /**
     * Gets the value of the agcyId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAgcyId() {
        return agcyId;
    }

    /**
     * Sets the value of the agcyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAgcyId(JAXBElement<String> value) {
        this.agcyId = value;
    }

    /**
     * Gets the value of the agcyOri property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAgcyOri() {
        return agcyOri;
    }

    /**
     * Sets the value of the agcyOri property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAgcyOri(JAXBElement<String> value) {
        this.agcyOri = value;
    }

    /**
     * Gets the value of the balDue property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getBalDue() {
        return balDue;
    }

    /**
     * Sets the value of the balDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setBalDue(JAXBElement<BigDecimal> value) {
        this.balDue = value;
    }

    /**
     * Gets the value of the caseNum property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCaseNum() {
        return caseNum;
    }

    /**
     * Sets the value of the caseNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCaseNum(JAXBElement<String> value) {
        this.caseNum = value;
    }

    /**
     * Gets the value of the caseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCaseStatus() {
        return caseStatus;
    }

    /**
     * Sets the value of the caseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCaseStatus(JAXBElement<String> value) {
        this.caseStatus = value;
    }

    /**
     * Gets the value of the caseStatusDesc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCaseStatusDesc() {
        return caseStatusDesc;
    }

    /**
     * Sets the value of the caseStatusDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCaseStatusDesc(JAXBElement<String> value) {
        this.caseStatusDesc = value;
    }

    /**
     * Gets the value of the chrgCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getChrgCode() {
        return chrgCode;
    }

    /**
     * Sets the value of the chrgCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setChrgCode(JAXBElement<String> value) {
        this.chrgCode = value;
    }

    /**
     * Gets the value of the chrgDesc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getChrgDesc() {
        return chrgDesc;
    }

    /**
     * Sets the value of the chrgDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setChrgDesc(JAXBElement<String> value) {
        this.chrgDesc = value;
    }

    /**
     * Gets the value of the courtName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCourtName() {
        return courtName;
    }

    /**
     * Sets the value of the courtName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCourtName(JAXBElement<String> value) {
        this.courtName = value;
    }

    /**
     * Gets the value of the deftName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDeftName() {
        return deftName;
    }

    /**
     * Sets the value of the deftName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDeftName(JAXBElement<String> value) {
        this.deftName = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDob() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDob(XMLGregorianCalendar value) {
        this.dob = value;
    }

    /**
     * Gets the value of the isAgcyPlus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAgcyPlus() {
        return isAgcyPlus;
    }

    /**
     * Sets the value of the isAgcyPlus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAgcyPlus(Boolean value) {
        this.isAgcyPlus = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLastName(JAXBElement<String> value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the nextDktCrtRoom property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNextDktCrtRoom() {
        return nextDktCrtRoom;
    }

    /**
     * Sets the value of the nextDktCrtRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNextDktCrtRoom(JAXBElement<String> value) {
        this.nextDktCrtRoom = value;
    }

    /**
     * Gets the value of the nextDktDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNextDktDate() {
        return nextDktDate;
    }

    /**
     * Sets the value of the nextDktDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNextDktDate(XMLGregorianCalendar value) {
        this.nextDktDate = value;
    }

    /**
     * Gets the value of the pbmStatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPbmStatus() {
        return pbmStatus;
    }

    /**
     * Sets the value of the pbmStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPbmStatus(JAXBElement<String> value) {
        this.pbmStatus = value;
    }

    /**
     * Gets the value of the pymtUrl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPymtUrl() {
        return pymtUrl;
    }

    /**
     * Sets the value of the pymtUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPymtUrl(JAXBElement<String> value) {
        this.pymtUrl = value;
    }

    /**
     * Gets the value of the recId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * Sets the value of the recId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRecId(Integer value) {
        this.recId = value;
    }

    /**
     * Gets the value of the tktNum property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTktNum() {
        return tktNum;
    }

    /**
     * Sets the value of the tktNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTktNum(JAXBElement<String> value) {
        this.tktNum = value;
    }

    /**
     * Gets the value of the violDttm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getViolDttm() {
        return violDttm;
    }

    /**
     * Sets the value of the violDttm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setViolDttm(XMLGregorianCalendar value) {
        this.violDttm = value;
    }

}
