//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 07:26:16 PM CDT 
//


package svc.data.citations.datasources.rejis.org.datacontract.schemas._2004._07.rejis_services_court;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.datacontract.schemas._2004._07.rejis_services_court package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ArrayOfAgencyOri_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "ArrayOfAgencyOri");
    private final static QName _AgencyOri_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "AgencyOri");
    private final static QName _ArrayOfCaseIndex_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "ArrayOfCaseIndex");
    private final static QName _CaseIndex_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "CaseIndex");
    private final static QName _FullCaseView_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "FullCaseView");
    private final static QName _CaseIndexAgcyId_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "AgcyId");
    private final static QName _CaseIndexAgcyOri_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "AgcyOri");
    private final static QName _CaseIndexBalDue_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "BalDue");
    private final static QName _CaseIndexCaseNum_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "CaseNum");
    private final static QName _CaseIndexCaseStatus_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "CaseStatus");
    private final static QName _CaseIndexCaseStatusDesc_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "CaseStatusDesc");
    private final static QName _CaseIndexChrgCode_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "ChrgCode");
    private final static QName _CaseIndexChrgDesc_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "ChrgDesc");
    private final static QName _CaseIndexCourtName_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "CourtName");
    private final static QName _CaseIndexDeftName_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "DeftName");
    private final static QName _CaseIndexLastName_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "LastName");
    private final static QName _CaseIndexNextDktCrtRoom_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "NextDktCrtRoom");
    private final static QName _CaseIndexPbmStatus_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "PbmStatus");
    private final static QName _CaseIndexPymtUrl_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "PymtUrl");
    private final static QName _CaseIndexTktNum_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "TktNum");
    private final static QName _AgencyOriAgcyId_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "agcy_id");
    private final static QName _AgencyOriCrtOri_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "crt_ori");
    private final static QName _AgencyOriCrtState_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "crt_state");
    private final static QName _AgencyOriCrtTitle_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "crt_title");
    private final static QName _AgencyOriDbapp_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "dbapp");
    private final static QName _FullCaseViewAssdAmt_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "AssdAmt");
    private final static QName _FullCaseViewBondSetAmt_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "BondSetAmt");
    private final static QName _FullCaseViewCourtWebSite_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "CourtWebSite");
    private final static QName _FullCaseViewDefAttyAddr_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "DefAttyAddr");
    private final static QName _FullCaseViewDefAttyName_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "DefAttyName");
    private final static QName _FullCaseViewDefAttyPhone_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "DefAttyPhone");
    private final static QName _FullCaseViewDeftAddr_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "DeftAddr");
    private final static QName _FullCaseViewDispDesc_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "DispDesc");
    private final static QName _FullCaseViewIssuingAgcy_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "IssuingAgcy");
    private final static QName _FullCaseViewJudgeName_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "JudgeName");
    private final static QName _FullCaseViewNextDktCrtRm_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "NextDktCrtRm");
    private final static QName _FullCaseViewOcn_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "Ocn");
    private final static QName _FullCaseViewOrigDktCrtRm_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "OrigDktCrtRm");
    private final static QName _FullCaseViewPlea_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "Plea");
    private final static QName _FullCaseViewProbDays_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "ProbDays");
    private final static QName _FullCaseViewProbMonths_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "ProbMonths");
    private final static QName _FullCaseViewProbYears_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "ProbYears");
    private final static QName _FullCaseViewSentExecCode_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "SentExecCode");
    private final static QName _FullCaseViewSentExecDesc_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "SentExecDesc");
    private final static QName _FullCaseViewStateChrg_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "StateChrg");
    private final static QName _FullCaseViewStatute_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "Statute");
    private final static QName _FullCaseViewViolAddr_QNAME = new QName("http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", "ViolAddr");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.datacontract.schemas._2004._07.rejis_services_court
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrayOfAgencyOri }
     * 
     */
    public ArrayOfAgencyOri createArrayOfAgencyOri() {
        return new ArrayOfAgencyOri();
    }

    /**
     * Create an instance of {@link ArrayOfCaseIndex }
     * 
     */
    public ArrayOfCaseIndex createArrayOfCaseIndex() {
        return new ArrayOfCaseIndex();
    }

    /**
     * Create an instance of {@link FullCaseView }
     * 
     */
    public FullCaseView createFullCaseView() {
        return new FullCaseView();
    }

    /**
     * Create an instance of {@link AgencyOri }
     * 
     */
    public AgencyOri createAgencyOri() {
        return new AgencyOri();
    }

    /**
     * Create an instance of {@link CaseIndex }
     * 
     */
    public CaseIndex createCaseIndex() {
        return new CaseIndex();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfAgencyOri }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "ArrayOfAgencyOri")
    public JAXBElement<ArrayOfAgencyOri> createArrayOfAgencyOri(ArrayOfAgencyOri value) {
        return new JAXBElement<ArrayOfAgencyOri>(_ArrayOfAgencyOri_QNAME, ArrayOfAgencyOri.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgencyOri }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "AgencyOri")
    public JAXBElement<AgencyOri> createAgencyOri(AgencyOri value) {
        return new JAXBElement<AgencyOri>(_AgencyOri_QNAME, AgencyOri.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfCaseIndex }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "ArrayOfCaseIndex")
    public JAXBElement<ArrayOfCaseIndex> createArrayOfCaseIndex(ArrayOfCaseIndex value) {
        return new JAXBElement<ArrayOfCaseIndex>(_ArrayOfCaseIndex_QNAME, ArrayOfCaseIndex.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CaseIndex }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "CaseIndex")
    public JAXBElement<CaseIndex> createCaseIndex(CaseIndex value) {
        return new JAXBElement<CaseIndex>(_CaseIndex_QNAME, CaseIndex.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FullCaseView }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "FullCaseView")
    public JAXBElement<FullCaseView> createFullCaseView(FullCaseView value) {
        return new JAXBElement<FullCaseView>(_FullCaseView_QNAME, FullCaseView.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "AgcyId", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexAgcyId(String value) {
        return new JAXBElement<String>(_CaseIndexAgcyId_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "AgcyOri", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexAgcyOri(String value) {
        return new JAXBElement<String>(_CaseIndexAgcyOri_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "BalDue", scope = CaseIndex.class)
    public JAXBElement<BigDecimal> createCaseIndexBalDue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CaseIndexBalDue_QNAME, BigDecimal.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "CaseNum", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexCaseNum(String value) {
        return new JAXBElement<String>(_CaseIndexCaseNum_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "CaseStatus", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexCaseStatus(String value) {
        return new JAXBElement<String>(_CaseIndexCaseStatus_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "CaseStatusDesc", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexCaseStatusDesc(String value) {
        return new JAXBElement<String>(_CaseIndexCaseStatusDesc_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "ChrgCode", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexChrgCode(String value) {
        return new JAXBElement<String>(_CaseIndexChrgCode_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "ChrgDesc", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexChrgDesc(String value) {
        return new JAXBElement<String>(_CaseIndexChrgDesc_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "CourtName", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexCourtName(String value) {
        return new JAXBElement<String>(_CaseIndexCourtName_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "DeftName", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexDeftName(String value) {
        return new JAXBElement<String>(_CaseIndexDeftName_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "LastName", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexLastName(String value) {
        return new JAXBElement<String>(_CaseIndexLastName_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "NextDktCrtRoom", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexNextDktCrtRoom(String value) {
        return new JAXBElement<String>(_CaseIndexNextDktCrtRoom_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "PbmStatus", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexPbmStatus(String value) {
        return new JAXBElement<String>(_CaseIndexPbmStatus_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "PymtUrl", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexPymtUrl(String value) {
        return new JAXBElement<String>(_CaseIndexPymtUrl_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "TktNum", scope = CaseIndex.class)
    public JAXBElement<String> createCaseIndexTktNum(String value) {
        return new JAXBElement<String>(_CaseIndexTktNum_QNAME, String.class, CaseIndex.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "agcy_id", scope = AgencyOri.class)
    public JAXBElement<String> createAgencyOriAgcyId(String value) {
        return new JAXBElement<String>(_AgencyOriAgcyId_QNAME, String.class, AgencyOri.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "crt_ori", scope = AgencyOri.class)
    public JAXBElement<String> createAgencyOriCrtOri(String value) {
        return new JAXBElement<String>(_AgencyOriCrtOri_QNAME, String.class, AgencyOri.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "crt_state", scope = AgencyOri.class)
    public JAXBElement<String> createAgencyOriCrtState(String value) {
        return new JAXBElement<String>(_AgencyOriCrtState_QNAME, String.class, AgencyOri.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "crt_title", scope = AgencyOri.class)
    public JAXBElement<String> createAgencyOriCrtTitle(String value) {
        return new JAXBElement<String>(_AgencyOriCrtTitle_QNAME, String.class, AgencyOri.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "dbapp", scope = AgencyOri.class)
    public JAXBElement<String> createAgencyOriDbapp(String value) {
        return new JAXBElement<String>(_AgencyOriDbapp_QNAME, String.class, AgencyOri.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "AgcyId", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewAgcyId(String value) {
        return new JAXBElement<String>(_CaseIndexAgcyId_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "AgcyOri", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewAgcyOri(String value) {
        return new JAXBElement<String>(_CaseIndexAgcyOri_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "AssdAmt", scope = FullCaseView.class)
    public JAXBElement<BigDecimal> createFullCaseViewAssdAmt(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_FullCaseViewAssdAmt_QNAME, BigDecimal.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "BalDue", scope = FullCaseView.class)
    public JAXBElement<BigDecimal> createFullCaseViewBalDue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CaseIndexBalDue_QNAME, BigDecimal.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "BondSetAmt", scope = FullCaseView.class)
    public JAXBElement<BigDecimal> createFullCaseViewBondSetAmt(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_FullCaseViewBondSetAmt_QNAME, BigDecimal.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "CaseNum", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewCaseNum(String value) {
        return new JAXBElement<String>(_CaseIndexCaseNum_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "CaseStatus", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewCaseStatus(String value) {
        return new JAXBElement<String>(_CaseIndexCaseStatus_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "CaseStatusDesc", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewCaseStatusDesc(String value) {
        return new JAXBElement<String>(_CaseIndexCaseStatusDesc_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "ChrgCode", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewChrgCode(String value) {
        return new JAXBElement<String>(_CaseIndexChrgCode_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "ChrgDesc", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewChrgDesc(String value) {
        return new JAXBElement<String>(_CaseIndexChrgDesc_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "CourtName", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewCourtName(String value) {
        return new JAXBElement<String>(_CaseIndexCourtName_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "CourtWebSite", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewCourtWebSite(String value) {
        return new JAXBElement<String>(_FullCaseViewCourtWebSite_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "DefAttyAddr", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewDefAttyAddr(String value) {
        return new JAXBElement<String>(_FullCaseViewDefAttyAddr_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "DefAttyName", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewDefAttyName(String value) {
        return new JAXBElement<String>(_FullCaseViewDefAttyName_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "DefAttyPhone", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewDefAttyPhone(String value) {
        return new JAXBElement<String>(_FullCaseViewDefAttyPhone_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "DeftAddr", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewDeftAddr(String value) {
        return new JAXBElement<String>(_FullCaseViewDeftAddr_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "DeftName", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewDeftName(String value) {
        return new JAXBElement<String>(_CaseIndexDeftName_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "DispDesc", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewDispDesc(String value) {
        return new JAXBElement<String>(_FullCaseViewDispDesc_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "IssuingAgcy", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewIssuingAgcy(String value) {
        return new JAXBElement<String>(_FullCaseViewIssuingAgcy_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "JudgeName", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewJudgeName(String value) {
        return new JAXBElement<String>(_FullCaseViewJudgeName_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "LastName", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewLastName(String value) {
        return new JAXBElement<String>(_CaseIndexLastName_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "NextDktCrtRm", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewNextDktCrtRm(String value) {
        return new JAXBElement<String>(_FullCaseViewNextDktCrtRm_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "Ocn", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewOcn(String value) {
        return new JAXBElement<String>(_FullCaseViewOcn_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "OrigDktCrtRm", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewOrigDktCrtRm(String value) {
        return new JAXBElement<String>(_FullCaseViewOrigDktCrtRm_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "Plea", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewPlea(String value) {
        return new JAXBElement<String>(_FullCaseViewPlea_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "ProbDays", scope = FullCaseView.class)
    public JAXBElement<Integer> createFullCaseViewProbDays(Integer value) {
        return new JAXBElement<Integer>(_FullCaseViewProbDays_QNAME, Integer.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "ProbMonths", scope = FullCaseView.class)
    public JAXBElement<Integer> createFullCaseViewProbMonths(Integer value) {
        return new JAXBElement<Integer>(_FullCaseViewProbMonths_QNAME, Integer.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "ProbYears", scope = FullCaseView.class)
    public JAXBElement<Integer> createFullCaseViewProbYears(Integer value) {
        return new JAXBElement<Integer>(_FullCaseViewProbYears_QNAME, Integer.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "PymtUrl", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewPymtUrl(String value) {
        return new JAXBElement<String>(_CaseIndexPymtUrl_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "SentExecCode", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewSentExecCode(String value) {
        return new JAXBElement<String>(_FullCaseViewSentExecCode_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "SentExecDesc", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewSentExecDesc(String value) {
        return new JAXBElement<String>(_FullCaseViewSentExecDesc_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "StateChrg", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewStateChrg(String value) {
        return new JAXBElement<String>(_FullCaseViewStateChrg_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "Statute", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewStatute(String value) {
        return new JAXBElement<String>(_FullCaseViewStatute_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "TktNum", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewTktNum(String value) {
        return new JAXBElement<String>(_CaseIndexTktNum_QNAME, String.class, FullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", name = "ViolAddr", scope = FullCaseView.class)
    public JAXBElement<String> createFullCaseViewViolAddr(String value) {
        return new JAXBElement<String>(_FullCaseViewViolAddr_QNAME, String.class, FullCaseView.class, value);
    }

}
