//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 07:26:16 PM CDT 
//


package svc.data.citations.datasources.regis.org.tempuri;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="p_DktDttm" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="p_LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="p_FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="p_MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="p_AgcyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="p_PageNum" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="p_RowsPerPage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="p_TotalRows" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pDktDttm",
    "pLastName",
    "pFirstName",
    "pMiddleName",
    "pAgcyId",
    "pPageNum",
    "pRowsPerPage",
    "pTotalRows"
})
@XmlRootElement(name = "GetByDocketDateName")
public class GetByDocketDateName {

    @XmlElement(name = "p_DktDttm")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar pDktDttm;
    @XmlElementRef(name = "p_LastName", namespace = "http://tempuri.org/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> pLastName;
    @XmlElementRef(name = "p_FirstName", namespace = "http://tempuri.org/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> pFirstName;
    @XmlElementRef(name = "p_MiddleName", namespace = "http://tempuri.org/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> pMiddleName;
    @XmlElementRef(name = "p_AgcyId", namespace = "http://tempuri.org/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> pAgcyId;
    @XmlElement(name = "p_PageNum")
    protected Integer pPageNum;
    @XmlElement(name = "p_RowsPerPage")
    protected Integer pRowsPerPage;
    @XmlElement(name = "p_TotalRows")
    protected Integer pTotalRows;

    /**
     * Gets the value of the pDktDttm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPDktDttm() {
        return pDktDttm;
    }

    /**
     * Sets the value of the pDktDttm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPDktDttm(XMLGregorianCalendar value) {
        this.pDktDttm = value;
    }

    /**
     * Gets the value of the pLastName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPLastName() {
        return pLastName;
    }

    /**
     * Sets the value of the pLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPLastName(JAXBElement<String> value) {
        this.pLastName = value;
    }

    /**
     * Gets the value of the pFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPFirstName() {
        return pFirstName;
    }

    /**
     * Sets the value of the pFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPFirstName(JAXBElement<String> value) {
        this.pFirstName = value;
    }

    /**
     * Gets the value of the pMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPMiddleName() {
        return pMiddleName;
    }

    /**
     * Sets the value of the pMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPMiddleName(JAXBElement<String> value) {
        this.pMiddleName = value;
    }

    /**
     * Gets the value of the pAgcyId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPAgcyId() {
        return pAgcyId;
    }

    /**
     * Sets the value of the pAgcyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPAgcyId(JAXBElement<String> value) {
        this.pAgcyId = value;
    }

    /**
     * Gets the value of the pPageNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPPageNum() {
        return pPageNum;
    }

    /**
     * Sets the value of the pPageNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPPageNum(Integer value) {
        this.pPageNum = value;
    }

    /**
     * Gets the value of the pRowsPerPage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPRowsPerPage() {
        return pRowsPerPage;
    }

    /**
     * Sets the value of the pRowsPerPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPRowsPerPage(Integer value) {
        this.pRowsPerPage = value;
    }

    /**
     * Gets the value of the pTotalRows property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPTotalRows() {
        return pTotalRows;
    }

    /**
     * Sets the value of the pTotalRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPTotalRows(Integer value) {
        this.pTotalRows = value;
    }

}
