INSERT INTO judges(id,judge,court_id) VALUES (1,'Virginia Nye',1);
INSERT INTO judges(id,judge,court_id) VALUES (2,'William Buchholz II',2);
INSERT INTO judges(id,judge,court_id) VALUES (3,'John Duepner',3);
INSERT INTO judges(id,judge,court_id) VALUES (4,'Charles Kirksey',4);
INSERT INTO judges(id,judge,court_id) VALUES (5,'Sean O''Hagan',5);
INSERT INTO judges(id,judge,court_id) VALUES (6,'Thomas Flach',6);
INSERT INTO judges(id,judge,court_id) VALUES (7,'Jennifer Fisher',7);
INSERT INTO judges(id,judge,court_id) VALUES (8,'Brian Dunlop',8);
INSERT INTO judges(id,judge,court_id) VALUES (9,'John Duepner',9);
INSERT INTO judges(id,judge,court_id) VALUES (10,'William Buchholz II',10);
INSERT INTO judges(id,judge,court_id) VALUES (11,'Patrick Dignam',11);
INSERT INTO judges(id,judge,court_id) VALUES (12,'Joseph Larrew',12);
INSERT INTO judges(id,judge,court_id) VALUES (13,'Philip Ayers',13);
INSERT INTO judges(id,judge,court_id) VALUES (14,'William Buchholz II',14);
INSERT INTO judges(id,judge,court_id) VALUES (15,'Rick Brunk',15);
INSERT INTO judges(id,judge,court_id) VALUES (16,'April Porter',16);
INSERT INTO judges(id,judge,court_id) VALUES (17,'Joseph Dulles',17);
INSERT INTO judges(id,judge,court_id) VALUES (18,'Kevin Kelly',18);
INSERT INTO judges(id,judge,court_id) VALUES (19,'William Buchholz II',19);
INSERT INTO judges(id,judge,court_id) VALUES (20,'Dean Waldemer',20);
INSERT INTO judges(id,judge,court_id) VALUES (21,'John Newsham',21);
INSERT INTO judges(id,judge,court_id) VALUES (22,'Tim Engelmeyer',22);
INSERT INTO judges(id,judge,court_id) VALUES (23,'Andrea Niehoff',23);
INSERT INTO judges(id,judge,court_id) VALUES (24,'Donnell Smith',24);
INSERT INTO judges(id,judge,court_id) VALUES (25,'Charles Billings Jr.',25);
INSERT INTO judges(id,judge,court_id) VALUES (26,'Sam Alton',26);
INSERT INTO judges(id,judge,court_id) VALUES (27,'Donald Anderson',27);
INSERT INTO judges(id,judge,court_id) VALUES (28,'Rick Barry',28);
INSERT INTO judges(id,judge,court_id) VALUES (29,'Charles Billings Jr.',29);
INSERT INTO judges(id,judge,court_id) VALUES (30,'Roy Richter',30);
INSERT INTO judges(id,judge,court_id) VALUES (31,'Mark Burstein',31);
INSERT INTO judges(id,judge,court_id) VALUES (32,'Dan Boyle',32);
INSERT INTO judges(id,judge,court_id) VALUES (33,'William Burnet',33);
INSERT INTO judges(id,judge,court_id) VALUES (34,'Timothy Devereux',34);
INSERT INTO judges(id,judge,court_id) VALUES (35,'Celeste Endicott',35);
INSERT INTO judges(id,judge,court_id) VALUES (36,'Tonia Aldahdah',35);
INSERT INTO judges(id,judge,court_id) VALUES (37,'Steven Clark',36);
INSERT INTO judges(id,judge,court_id) VALUES (38,'Kevin Kelly',37);
INSERT INTO judges(id,judge,court_id) VALUES (39,'Philip Dennis',38);
INSERT INTO judges(id,judge,court_id) VALUES (40,'Victor Thompson',38);
INSERT INTO judges(id,judge,court_id) VALUES (41,'John Duepner',39);
INSERT INTO judges(id,judge,court_id) VALUES (42,'Charles Kirksey',40);
INSERT INTO judges(id,judge,court_id) VALUES (43,'Stephen O''Brien',41);
INSERT INTO judges(id,judge,court_id) VALUES (44,'Keith Cheung',42);
INSERT INTO judges(id,judge,court_id) VALUES (45,'Richard Bumb',44);
INSERT INTO judges(id,judge,court_id) VALUES (46,'Michael Gunn',45);
INSERT INTO judges(id,judge,court_id) VALUES (47,'Brian Dunlop',46);
INSERT INTO judges(id,judge,court_id) VALUES (48,'Ronald Wessel',47);
INSERT INTO judges(id,judge,court_id) VALUES (49,'Kevin Kelly',48);
INSERT INTO judges(id,judge,court_id) VALUES (50,'Jennifer Fisher',49);
INSERT INTO judges(id,judge,court_id) VALUES (51,'Raphael Norris',50);
INSERT INTO judges(id,judge,court_id) VALUES (52,'Daniel R. Brown',51);
INSERT INTO judges(id,judge,court_id) VALUES (53,'Craig J. Concannon',51);
INSERT INTO judges(id,judge,court_id) VALUES (54,'Chris Graville',52);
INSERT INTO judges(id,judge,court_id) VALUES (55,'Paul D''Agrosa',53);
INSERT INTO judges(id,judge,court_id) VALUES (56,'Frank Vatterott',54);
INSERT INTO judges(id,judge,court_id) VALUES (57,' Mason Klippel',54);
INSERT INTO judges(id,judge,court_id) VALUES (58,' Charles Billings',54);
INSERT INTO judges(id,judge,court_id) VALUES (59,'Daniel Leslie',55);
INSERT INTO judges(id,judge,court_id) VALUES (60,'Raphael Norris',56);
INSERT INTO judges(id,judge,court_id) VALUES (61,'Dan Hayes',57);
INSERT INTO judges(id,judge,court_id) VALUES (62,'Dan Diemar',57);
INSERT INTO judges(id,judge,court_id) VALUES (63,'Daniel Chartrand',58);
INSERT INTO judges(id,judge,court_id) VALUES (64,'Dean Plocher',59);
INSERT INTO judges(id,judge,court_id) VALUES (65,'Stephen O''Brien',60);
INSERT INTO judges(id,judge,court_id) VALUES (66,'Christopher McDonough',61);
INSERT INTO judges(id,judge,court_id) VALUES (67,'Mark Levitt',62);
INSERT INTO judges(id,judge,court_id) VALUES (68,'Sean O''Hagan',63);
INSERT INTO judges(id,judge,court_id) VALUES (69,'William Buchholz',63);
INSERT INTO judges(id,judge,court_id) VALUES (70,'Dennis Beckley',64);
INSERT INTO judges(id,judge,court_id) VALUES (71,'W. Laird Hetlage',65);
INSERT INTO judges(id,judge,court_id) VALUES (72,'Paul D''Agrosa',66);
INSERT INTO judges(id,judge,court_id) VALUES (73,'Phillip Ayers',67);
INSERT INTO judges(id,judge,court_id) VALUES (74,'Steven Clark',68);
INSERT INTO judges(id,judge,court_id) VALUES (75,'Wesley Bell (City website)',69);
INSERT INTO judges(id,judge,court_id) VALUES (76,'Raphael Norris (State)',69);
INSERT INTO judges(id,judge,court_id) VALUES (77,'Thomas Flach',70);
INSERT INTO judges(id,judge,court_id) VALUES (78,'William Goldstein',71);
INSERT INTO judges(id,judge,court_id) VALUES (79,'Daniel Chartrand',72);
INSERT INTO judges(id,judge,court_id) VALUES (80,'John Lord III',73);
INSERT INTO judges(id,judge,court_id) VALUES (81,'James Whitney',74);
INSERT INTO judges(id,judge,court_id) VALUES (82,'Charles Kirksey',75);
INSERT INTO judges(id,judge,court_id) VALUES (83,'Rick Brunk',76);
INSERT INTO judges(id,judge,court_id) VALUES (84,'Daniel Bruntrager',77);
INSERT INTO judges(id,judge,court_id) VALUES (85,'Kelly Clarkin',78);
INSERT INTO judges(id,judge,court_id) VALUES (86,'Thomas Clarkin',78);
INSERT INTO judges(id,judge,court_id) VALUES (87,' Daniel Brown',79);
INSERT INTO judges(id,judge,court_id) VALUES (88,'Celeste Endicott',79);
INSERT INTO judges(id,judge,court_id) VALUES (89,' Craig Cocannon',79);
INSERT INTO judges(id,judge,court_id) VALUES (90,' Tonia Aldahdah',79);
INSERT INTO judges(id,judge,court_id) VALUES (91,'Craig J. Cocannon',80);
