INSERT INTO municipalities(id,municipality_name,court_id) VALUES (1,'Ballwin',1);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (2,'Bella Villa',2);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (3,'Bellefontaine Neighbors',3);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (4,'Bellerive',4);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (5,'Bel-Nor',5);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (6,'Bel-Ridge',6);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (7,'Berkeley 1',7);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (8,'Beverly Hills',8);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (9,'Black Jack',9);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (10,'Breckenridge Hills',10);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (11,'Brentwood',11);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (12,'Bridgeton',12);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (13,'Calverton Park',13);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (14,'Charlack',14);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (15,'Chesterfield',15);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (16,'Clarkson Valley',16);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (17,'Clayton',17);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (18,'Cool Valley',18);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (19,'Country Club Hills',19);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (20,'Country Life Acres',20);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (21,'Crestwood',21);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (22,'Creve Coeur',22);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (23,'Crystal Lake Park',23);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (24,'Dellwood',24);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (25,'Des Peres',25);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (26,'Edmundson',26);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (27,'Ellisville',27);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (28,'Eureka',28);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (29,'Fenton',29);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (30,'Ferguson',30);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (31,'Flordell Hills',31);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (32,'Florissant',32);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (33,'Frontenac',23);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (34,'Glen Echo Park',4);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (35,'Glendale',33);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (36,'Grantwood Village',34);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (37,'Greendale',4);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (38,'Green Park',35);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (39,'Hanley Hills',36);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (40,'Hazelwood',37);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (41,'Hillsdale',38);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (42,'Huntleigh',23);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (43,'Jennings',39);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (44,'Kinloch',40);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (45,'Kirkwood',41);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (46,'Ladue',42);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (47,'Lakeshire',43);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (48,'Mackenzie',44);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (49,'Manchester',45);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (50,'Maplewood',46);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (51,'Marlborough',47);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (52,'Maryland Heights',48);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (53,'Moline Acres',49);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (54,'Normandy',4);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (55,'Northwoods',50);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (56,'Norwood Court',51);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (57,'Oakland',52);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (58,'Olivette',53);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (59,'Overland',54);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (60,'Pacific',55);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (61,'Pagedale',56);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (62,'Pasadena Hills',57);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (63,'Pasadena Park',58);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (64,'Pine Lawn',59);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (65,'Richmond Heights',60);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (66,'Riverview',61);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (67,'Rock Hill',62);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (68,'Shrewsbury',44);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (69,'St. Ann',63);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (70,'St. John',64);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (71,'Sunset Hills',65);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (72,'Sycamore Hills',64);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (73,'Town and Country',20);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (74,'Twin Oaks',35);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (75,'University City',66);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (76,'Uplands Park',67);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (77,'Valley Park',68);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (78,'Velda City',69);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (79,'Velda Village Hills',70);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (80,'Vinita Park',71);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (81,'Vinita Terrace',72);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (82,'Warson Woods',73);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (83,'Webster Groves',74);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (84,'Wellston',75);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (85,'Westwood',23);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (86,'Wilbur Park',35);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (87,'Wildwood',76);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (88,'Winchester',77);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (89,'Woodson Terrace',78);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (90,'Unincorporated Central St. Louis County',79);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (91,'Unincorporated West St. Louis County',80);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (92,'Unincorporated North St. Louis County',51);
INSERT INTO municipalities(id,municipality_name,court_id) VALUES (93,'Unincorporated South St. Louis County',35);
