INSERT INTO municipality(municipality_id,municipality_name) VALUES (1,'Ballwin');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (2,'Bella Villa');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (3,'Bellefontaine Neighbors');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (4,'Bellerive');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (5,'Bel-Nor');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (6,'Bel-Ridge');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (7,'Berkeley');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (8,'Beverly Hills');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (9,'Black Jack');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (10,'Breckenridge Hills');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (11,'Brentwood');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (12,'Bridgeton');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (13,'Calverton Park');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (14,'Charlack');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (15,'Chesterfield');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (16,'Clarkson Valley');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (17,'Clayton');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (18,'Cool Valley');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (19,'Country Club Hills');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (20,'Country Life Acres');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (21,'Crestwood');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (22,'Creve Coeur');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (23,'Crystal Lake Park');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (24,'Dellwood');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (25,'Des Peres');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (26,'Edmundson');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (27,'Ellisville');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (28,'Eureka');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (29,'Fenton');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (30,'Ferguson');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (31,'Flordell Hills');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (32,'Florissant');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (33,'Frontenac');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (34,'Glen Echo Park');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (35,'Glendale');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (36,'Grantwood Village');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (37,'Greendale');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (38,'Green Park');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (39,'Hanley Hills');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (40,'Hazelwood');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (41,'Hillsdale');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (42,'Huntleigh');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (43,'Jennings');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (44,'Kinloch');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (45,'Kirkwood');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (46,'Ladue');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (47,'Lakeshire');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (48,'Mackenzie');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (49,'Manchester');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (50,'Maplewood');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (51,'Marlborough');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (52,'Maryland Heights');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (53,'Moline Acres');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (54,'Normandy');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (55,'Northwoods');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (56,'Norwood Court');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (57,'Oakland');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (58,'Olivette');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (59,'Overland');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (60,'Pacific');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (61,'Pagedale');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (62,'Pasadena Hills');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (63,'Pasadena Park');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (64,'Pine Lawn');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (65,'Richmond Heights');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (66,'Riverview');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (67,'Rock Hill');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (68,'Shrewsbury');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (69,'St. Ann');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (70,'St. John');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (71,'Sunset Hills');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (72,'Sycamore Hills');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (73,'Town and Country');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (74,'Twin Oaks');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (75,'University City');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (76,'Uplands Park');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (77,'Valley Park');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (78,'Velda City');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (79,'Velda Village Hills');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (80,'Vinita Park');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (81,'Vinita Terrace');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (82,'Warson Woods');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (83,'Webster Groves');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (84,'Wellston');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (85,'Westwood');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (86,'Wilbur Park');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (87,'Wildwood');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (88,'Winchester');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (89,'Woodson Terrace');
INSERT INTO municipality(municipality_id,municipality_name) VALUES (90,'Unincorporated St. Louis County');
