INSERT INTO municipalities(id,municipality,court_id) VALUES (1,'Ballwin',21);
INSERT INTO municipalities(id,municipality,court_id) VALUES (2,'Bella Villa',6);
INSERT INTO municipalities(id,municipality,court_id) VALUES (3,'Bellefontaine Neighbors',70);
INSERT INTO municipalities(id,municipality,court_id) VALUES (4,'Bel-Nor',56);
INSERT INTO municipalities(id,municipality,court_id) VALUES (5,'Bel-Ridge',61);
INSERT INTO municipalities(id,municipality,court_id) VALUES (6,'Berkeley 1',72);
INSERT INTO municipalities(id,municipality,court_id) VALUES (7,'Berkeley 2',73);
INSERT INTO municipalities(id,municipality,court_id) VALUES (8,'Beverly Hills',51);
INSERT INTO municipalities(id,municipality,court_id) VALUES (9,'Black Jack',80);
INSERT INTO municipalities(id,municipality,court_id) VALUES (10,'Breckenridge Hills',63);
INSERT INTO municipalities(id,municipality,court_id) VALUES (11,'Brentwood',27);
INSERT INTO municipalities(id,municipality,court_id) VALUES (12,'Bridgeton',76);
INSERT INTO municipalities(id,municipality,court_id) VALUES (13,'Calverton Park',77);
INSERT INTO municipalities(id,municipality,court_id) VALUES (14,'Charlack',49);
INSERT INTO municipalities(id,municipality,court_id) VALUES (15,'Chesterfield',36);
INSERT INTO municipalities(id,municipality,court_id) VALUES (16,'Clarkson Valley',24);
INSERT INTO municipalities(id,municipality,court_id) VALUES (17,'Clayton',34);
INSERT INTO municipalities(id,municipality,court_id) VALUES (18,'Cool Valley',55);
INSERT INTO municipalities(id,municipality,court_id) VALUES (19,'Country Club Hills',64);
INSERT INTO municipalities(id,municipality,court_id) VALUES (20,'Crestwood',10);
INSERT INTO municipalities(id,municipality,court_id) VALUES (21,'Creve Coeur',35);
INSERT INTO municipalities(id,municipality,court_id) VALUES (22,'Dellwood',74);
INSERT INTO municipalities(id,municipality,court_id) VALUES (23,'Des Peres',23);
INSERT INTO municipalities(id,municipality,court_id) VALUES (24,'Edmundson',67);
INSERT INTO municipalities(id,municipality,court_id) VALUES (25,'Ellisville',18);
INSERT INTO municipalities(id,municipality,court_id) VALUES (26,'Eureka',2);
INSERT INTO municipalities(id,municipality,court_id) VALUES (27,'Fenton',4);
INSERT INTO municipalities(id,municipality,court_id) VALUES (28,'Ferguson',71);
INSERT INTO municipalities(id,municipality,court_id) VALUES (29,'Flordell Hills',62);
INSERT INTO municipalities(id,municipality,court_id) VALUES (30,'Florissant',81);
INSERT INTO municipalities(id,municipality,court_id) VALUES (31,'Frontenac',31);
INSERT INTO municipalities(id,municipality,court_id) VALUES (32,'Glendale',16);
INSERT INTO municipalities(id,municipality,court_id) VALUES (33,'Grantwood Village',8);
INSERT INTO municipalities(id,municipality,court_id) VALUES (34,'Greendale',54);
INSERT INTO municipalities(id,municipality,court_id) VALUES (35,'Hanley Hills',41);
INSERT INTO municipalities(id,municipality,court_id) VALUES (36,'Hazelwood',79);
INSERT INTO municipalities(id,municipality,court_id) VALUES (37,'Hillsdale',43);
INSERT INTO municipalities(id,municipality,court_id) VALUES (38,'Jennings',58);
INSERT INTO municipalities(id,municipality,court_id) VALUES (39,'Kinloch',68);
INSERT INTO municipalities(id,municipality,court_id) VALUES (40,'Kirkwood',12);
INSERT INTO municipalities(id,municipality,court_id) VALUES (41,'Ladue',32);
INSERT INTO municipalities(id,municipality,court_id) VALUES (42,'Lakeshire',5);
INSERT INTO municipalities(id,municipality,court_id) VALUES (43,'Mackenzie',19);
INSERT INTO municipalities(id,municipality,court_id) VALUES (44,'Manchester',20);
INSERT INTO municipalities(id,municipality,court_id) VALUES (45,'Maplewood',26);
INSERT INTO municipalities(id,municipality,court_id) VALUES (46,'Marlborough',11);
INSERT INTO municipalities(id,municipality,court_id) VALUES (47,'Maryland Heights',60);
INSERT INTO municipalities(id,municipality,court_id) VALUES (48,'Moline Acres',75);
INSERT INTO municipalities(id,municipality,court_id) VALUES (49,'Normandy',54);
INSERT INTO municipalities(id,municipality,court_id) VALUES (50,'Northwoods',53);
INSERT INTO municipalities(id,municipality,court_id) VALUES (51,'Oakland',14);
INSERT INTO municipalities(id,municipality,court_id) VALUES (52,'Olivette',38);
INSERT INTO municipalities(id,municipality,court_id) VALUES (53,'Overland',50);
INSERT INTO municipalities(id,municipality,court_id) VALUES (54,'Pacific',1);
INSERT INTO municipalities(id,municipality,court_id) VALUES (55,'Pagedale',40);
INSERT INTO municipalities(id,municipality,court_id) VALUES (56,'Pasadena Hills',52);
INSERT INTO municipalities(id,municipality,court_id) VALUES (57,'Pasadena Park',57);
INSERT INTO municipalities(id,municipality,court_id) VALUES (58,'Pine Lawn',45);
INSERT INTO municipalities(id,municipality,court_id) VALUES (59,'Richmond Heights',29);
INSERT INTO municipalities(id,municipality,court_id) VALUES (60,'Riverview',69);
INSERT INTO municipalities(id,municipality,court_id) VALUES (61,'Rock Hill',25);
INSERT INTO municipalities(id,municipality,court_id) VALUES (62,'Shrewsbury',19);
INSERT INTO municipalities(id,municipality,court_id) VALUES (63,'St. Ann',66);
INSERT INTO municipalities(id,municipality,court_id) VALUES (64,'St. John',59);
INSERT INTO municipalities(id,municipality,court_id) VALUES (65,'Sunset Hills',7);
INSERT INTO municipalities(id,municipality,court_id) VALUES (66,'Sycamore Hills',59);
INSERT INTO municipalities(id,municipality,court_id) VALUES (67,'Town and Country',30);
INSERT INTO municipalities(id,municipality,court_id) VALUES (68,'University City',37);
INSERT INTO municipalities(id,municipality,court_id) VALUES (69,'Uplands Park',47);
INSERT INTO municipalities(id,municipality,court_id) VALUES (70,'Valley Park',9);
INSERT INTO municipalities(id,municipality,court_id) VALUES (71,'Velda City',44);
INSERT INTO municipalities(id,municipality,court_id) VALUES (72,'Velda Village Hills',46);
INSERT INTO municipalities(id,municipality,court_id) VALUES (73,'Vinita Park',48);
INSERT INTO municipalities(id,municipality,court_id) VALUES (74,'Vinita Terrace',42);
INSERT INTO municipalities(id,municipality,court_id) VALUES (75,'Warson Woods',22);
INSERT INTO municipalities(id,municipality,court_id) VALUES (76,'Webster Groves',15);
INSERT INTO municipalities(id,municipality,court_id) VALUES (77,'Wellston',39);
INSERT INTO municipalities(id,municipality,court_id) VALUES (78,'Wildwood',13);
INSERT INTO municipalities(id,municipality,court_id) VALUES (79,'Winchester',17);
INSERT INTO municipalities(id,municipality,court_id) VALUES (80,'Woodson Terrace',65);
INSERT INTO municipalities(id,municipality,court_id) VALUES (81,'Unincorporated Central St. Louis County',33);
INSERT INTO municipalities(id,municipality,court_id) VALUES (82,'Unincorporated West St. Louis County',28);
INSERT INTO municipalities(id,municipality,court_id) VALUES (83,'Unincorporated North St. Louis County',78);
INSERT INTO municipalities(id,municipality,court_id) VALUES (84,'Unincorporated South St. Louis County',3);
