//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 07:26:16 PM CDT 
//


package svc.data.citations.datasources.rejis.org.tempuri;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import svc.data.citations.datasources.rejis.org.datacontract.schemas._2004._07.rejis_services_court.*;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.tempuri package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAgcyIdOriListResponseGetAgcyIdOriListResult_QNAME = new QName("http://tempuri.org/", "GetAgcyIdOriListResult");
    private final static QName _GetByLastFirstDobPLastName_QNAME = new QName("http://tempuri.org/", "p_LastName");
    private final static QName _GetByLastFirstDobPFirstName_QNAME = new QName("http://tempuri.org/", "p_FirstName");
    private final static QName _GetByLastFirstDobPMiddleName_QNAME = new QName("http://tempuri.org/", "p_MiddleName");
    private final static QName _GetByLastFirstDobPAgcyId_QNAME = new QName("http://tempuri.org/", "p_agcyId");
    private final static QName _GetByLastFirstDobResponseGetByLastFirstDobResult_QNAME = new QName("http://tempuri.org/", "GetByLastFirstDobResult");
    private final static QName _GetByTicketNumberPTicketNum_QNAME = new QName("http://tempuri.org/", "p_ticketNum");
    private final static QName _GetByTicketNumberResponseGetByTicketNumberResult_QNAME = new QName("http://tempuri.org/", "GetByTicketNumberResult");
    private final static QName _GetByDocketDateNamePAgcyId_QNAME = new QName("http://tempuri.org/", "p_AgcyId");
    private final static QName _GetByDocketDateNameResponseGetByDocketDateNameResult_QNAME = new QName("http://tempuri.org/", "GetByDocketDateNameResult");
    private final static QName _GetByLicStatePVehLicNum_QNAME = new QName("http://tempuri.org/", "p_VehLicNum");
    private final static QName _GetByLicStatePVehLicState_QNAME = new QName("http://tempuri.org/", "p_VehLicState");
    private final static QName _GetByLicStateResponseGetByLicStateResult_QNAME = new QName("http://tempuri.org/", "GetByLicStateResult");
    private final static QName _GetByViolFilingDateResponseGetByViolFilingDateResult_QNAME = new QName("http://tempuri.org/", "GetByViolFilingDateResult");
    private final static QName _GetFullCaseViewResponseGetFullCaseViewResult_QNAME = new QName("http://tempuri.org/", "GetFullCaseViewResult");
    private final static QName _TestFuncPAgencyORI_QNAME = new QName("http://tempuri.org/", "p_agencyORI");
    private final static QName _TestFuncPParm2_QNAME = new QName("http://tempuri.org/", "p_parm2");
    private final static QName _TestFuncResponseTestFuncResult_QNAME = new QName("http://tempuri.org/", "testFuncResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.tempuri
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAgcyIdOriList }
     * 
     */
    public GetAgcyIdOriList createGetAgcyIdOriList() {
        return new GetAgcyIdOriList();
    }

    /**
     * Create an instance of {@link GetAgcyIdOriListResponse }
     * 
     */
    public GetAgcyIdOriListResponse createGetAgcyIdOriListResponse() {
        return new GetAgcyIdOriListResponse();
    }

    /**
     * Create an instance of {@link GetByLastFirstDob }
     * 
     */
    public GetByLastFirstDob createGetByLastFirstDob() {
        return new GetByLastFirstDob();
    }

    /**
     * Create an instance of {@link GetByLastFirstDobResponse }
     * 
     */
    public GetByLastFirstDobResponse createGetByLastFirstDobResponse() {
        return new GetByLastFirstDobResponse();
    }

    /**
     * Create an instance of {@link GetByTicketNumber }
     * 
     */
    public GetByTicketNumber createGetByTicketNumber() {
        return new GetByTicketNumber();
    }

    /**
     * Create an instance of {@link GetByTicketNumberResponse }
     * 
     */
    public GetByTicketNumberResponse createGetByTicketNumberResponse() {
        return new GetByTicketNumberResponse();
    }

    /**
     * Create an instance of {@link GetByDocketDateName }
     * 
     */
    public GetByDocketDateName createGetByDocketDateName() {
        return new GetByDocketDateName();
    }

    /**
     * Create an instance of {@link GetByDocketDateNameResponse }
     * 
     */
    public GetByDocketDateNameResponse createGetByDocketDateNameResponse() {
        return new GetByDocketDateNameResponse();
    }

    /**
     * Create an instance of {@link GetByLicState }
     * 
     */
    public GetByLicState createGetByLicState() {
        return new GetByLicState();
    }

    /**
     * Create an instance of {@link GetByLicStateResponse }
     * 
     */
    public GetByLicStateResponse createGetByLicStateResponse() {
        return new GetByLicStateResponse();
    }

    /**
     * Create an instance of {@link GetByViolFilingDate }
     * 
     */
    public GetByViolFilingDate createGetByViolFilingDate() {
        return new GetByViolFilingDate();
    }

    /**
     * Create an instance of {@link GetByViolFilingDateResponse }
     * 
     */
    public GetByViolFilingDateResponse createGetByViolFilingDateResponse() {
        return new GetByViolFilingDateResponse();
    }

    /**
     * Create an instance of {@link GetFullCaseView }
     * 
     */
    public GetFullCaseView createGetFullCaseView() {
        return new GetFullCaseView();
    }

    /**
     * Create an instance of {@link GetFullCaseViewResponse }
     * 
     */
    public GetFullCaseViewResponse createGetFullCaseViewResponse() {
        return new GetFullCaseViewResponse();
    }

    /**
     * Create an instance of {@link TestFunc }
     * 
     */
    public TestFunc createTestFunc() {
        return new TestFunc();
    }

    /**
     * Create an instance of {@link TestFuncResponse }
     * 
     */
    public TestFuncResponse createTestFuncResponse() {
        return new TestFuncResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfAgencyOri }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetAgcyIdOriListResult", scope = GetAgcyIdOriListResponse.class)
    public JAXBElement<ArrayOfAgencyOri> createGetAgcyIdOriListResponseGetAgcyIdOriListResult(ArrayOfAgencyOri value) {
        return new JAXBElement<ArrayOfAgencyOri>(_GetAgcyIdOriListResponseGetAgcyIdOriListResult_QNAME, ArrayOfAgencyOri.class, GetAgcyIdOriListResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_LastName", scope = GetByLastFirstDob.class)
    public JAXBElement<String> createGetByLastFirstDobPLastName(String value) {
        return new JAXBElement<String>(_GetByLastFirstDobPLastName_QNAME, String.class, GetByLastFirstDob.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_FirstName", scope = GetByLastFirstDob.class)
    public JAXBElement<String> createGetByLastFirstDobPFirstName(String value) {
        return new JAXBElement<String>(_GetByLastFirstDobPFirstName_QNAME, String.class, GetByLastFirstDob.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_MiddleName", scope = GetByLastFirstDob.class)
    public JAXBElement<String> createGetByLastFirstDobPMiddleName(String value) {
        return new JAXBElement<String>(_GetByLastFirstDobPMiddleName_QNAME, String.class, GetByLastFirstDob.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_agcyId", scope = GetByLastFirstDob.class)
    public JAXBElement<String> createGetByLastFirstDobPAgcyId(String value) {
        return new JAXBElement<String>(_GetByLastFirstDobPAgcyId_QNAME, String.class, GetByLastFirstDob.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfCaseIndex }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetByLastFirstDobResult", scope = GetByLastFirstDobResponse.class)
    public JAXBElement<ArrayOfCaseIndex> createGetByLastFirstDobResponseGetByLastFirstDobResult(ArrayOfCaseIndex value) {
        return new JAXBElement<ArrayOfCaseIndex>(_GetByLastFirstDobResponseGetByLastFirstDobResult_QNAME, ArrayOfCaseIndex.class, GetByLastFirstDobResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_ticketNum", scope = GetByTicketNumber.class)
    public JAXBElement<String> createGetByTicketNumberPTicketNum(String value) {
        return new JAXBElement<String>(_GetByTicketNumberPTicketNum_QNAME, String.class, GetByTicketNumber.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_agcyId", scope = GetByTicketNumber.class)
    public JAXBElement<String> createGetByTicketNumberPAgcyId(String value) {
        return new JAXBElement<String>(_GetByLastFirstDobPAgcyId_QNAME, String.class, GetByTicketNumber.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfCaseIndex }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetByTicketNumberResult", scope = GetByTicketNumberResponse.class)
    public JAXBElement<ArrayOfCaseIndex> createGetByTicketNumberResponseGetByTicketNumberResult(ArrayOfCaseIndex value) {
        return new JAXBElement<ArrayOfCaseIndex>(_GetByTicketNumberResponseGetByTicketNumberResult_QNAME, ArrayOfCaseIndex.class, GetByTicketNumberResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_LastName", scope = GetByDocketDateName.class)
    public JAXBElement<String> createGetByDocketDateNamePLastName(String value) {
        return new JAXBElement<String>(_GetByLastFirstDobPLastName_QNAME, String.class, GetByDocketDateName.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_FirstName", scope = GetByDocketDateName.class)
    public JAXBElement<String> createGetByDocketDateNamePFirstName(String value) {
        return new JAXBElement<String>(_GetByLastFirstDobPFirstName_QNAME, String.class, GetByDocketDateName.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_MiddleName", scope = GetByDocketDateName.class)
    public JAXBElement<String> createGetByDocketDateNamePMiddleName(String value) {
        return new JAXBElement<String>(_GetByLastFirstDobPMiddleName_QNAME, String.class, GetByDocketDateName.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_AgcyId", scope = GetByDocketDateName.class)
    public JAXBElement<String> createGetByDocketDateNamePAgcyId(String value) {
        return new JAXBElement<String>(_GetByDocketDateNamePAgcyId_QNAME, String.class, GetByDocketDateName.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfCaseIndex }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetByDocketDateNameResult", scope = GetByDocketDateNameResponse.class)
    public JAXBElement<ArrayOfCaseIndex> createGetByDocketDateNameResponseGetByDocketDateNameResult(ArrayOfCaseIndex value) {
        return new JAXBElement<ArrayOfCaseIndex>(_GetByDocketDateNameResponseGetByDocketDateNameResult_QNAME, ArrayOfCaseIndex.class, GetByDocketDateNameResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_VehLicNum", scope = GetByLicState.class)
    public JAXBElement<String> createGetByLicStatePVehLicNum(String value) {
        return new JAXBElement<String>(_GetByLicStatePVehLicNum_QNAME, String.class, GetByLicState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_VehLicState", scope = GetByLicState.class)
    public JAXBElement<String> createGetByLicStatePVehLicState(String value) {
        return new JAXBElement<String>(_GetByLicStatePVehLicState_QNAME, String.class, GetByLicState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_LastName", scope = GetByLicState.class)
    public JAXBElement<String> createGetByLicStatePLastName(String value) {
        return new JAXBElement<String>(_GetByLastFirstDobPLastName_QNAME, String.class, GetByLicState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_AgcyId", scope = GetByLicState.class)
    public JAXBElement<String> createGetByLicStatePAgcyId(String value) {
        return new JAXBElement<String>(_GetByDocketDateNamePAgcyId_QNAME, String.class, GetByLicState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfCaseIndex }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetByLicStateResult", scope = GetByLicStateResponse.class)
    public JAXBElement<ArrayOfCaseIndex> createGetByLicStateResponseGetByLicStateResult(ArrayOfCaseIndex value) {
        return new JAXBElement<ArrayOfCaseIndex>(_GetByLicStateResponseGetByLicStateResult_QNAME, ArrayOfCaseIndex.class, GetByLicStateResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_AgcyId", scope = GetByViolFilingDate.class)
    public JAXBElement<String> createGetByViolFilingDatePAgcyId(String value) {
        return new JAXBElement<String>(_GetByDocketDateNamePAgcyId_QNAME, String.class, GetByViolFilingDate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfCaseIndex }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetByViolFilingDateResult", scope = GetByViolFilingDateResponse.class)
    public JAXBElement<ArrayOfCaseIndex> createGetByViolFilingDateResponseGetByViolFilingDateResult(ArrayOfCaseIndex value) {
        return new JAXBElement<ArrayOfCaseIndex>(_GetByViolFilingDateResponseGetByViolFilingDateResult_QNAME, ArrayOfCaseIndex.class, GetByViolFilingDateResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_AgcyId", scope = GetFullCaseView.class)
    public JAXBElement<String> createGetFullCaseViewPAgcyId(String value) {
        return new JAXBElement<String>(_GetByDocketDateNamePAgcyId_QNAME, String.class, GetFullCaseView.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FullCaseView }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetFullCaseViewResult", scope = GetFullCaseViewResponse.class)
    public JAXBElement<FullCaseView> createGetFullCaseViewResponseGetFullCaseViewResult(FullCaseView value) {
        return new JAXBElement<FullCaseView>(_GetFullCaseViewResponseGetFullCaseViewResult_QNAME, FullCaseView.class, GetFullCaseViewResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_agencyORI", scope = TestFunc.class)
    public JAXBElement<String> createTestFuncPAgencyORI(String value) {
        return new JAXBElement<String>(_TestFuncPAgencyORI_QNAME, String.class, TestFunc.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "p_parm2", scope = TestFunc.class)
    public JAXBElement<String> createTestFuncPParm2(String value) {
        return new JAXBElement<String>(_TestFuncPParm2_QNAME, String.class, TestFunc.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "testFuncResult", scope = TestFuncResponse.class)
    public JAXBElement<String> createTestFuncResponseTestFuncResult(String value) {
        return new JAXBElement<String>(_TestFuncResponseTestFuncResult_QNAME, String.class, TestFuncResponse.class, value);
    }

}
