//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 07:26:16 PM CDT 
//


package svc.data.citations.datasources.regis.org.datacontract.schemas._2004._07.rejis_services_court;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AgencyOri complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AgencyOri"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="agcy_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="crt_ori" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="crt_state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="crt_title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dbapp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AgencyOri", propOrder = {
    "agcyId",
    "crtOri",
    "crtState",
    "crtTitle",
    "dbapp"
})
public class AgencyOri {

    @XmlElementRef(name = "agcy_id", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> agcyId;
    @XmlElementRef(name = "crt_ori", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> crtOri;
    @XmlElementRef(name = "crt_state", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> crtState;
    @XmlElementRef(name = "crt_title", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> crtTitle;
    @XmlElementRef(name = "dbapp", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dbapp;

    /**
     * Gets the value of the agcyId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAgcyId() {
        return agcyId;
    }

    /**
     * Sets the value of the agcyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAgcyId(JAXBElement<String> value) {
        this.agcyId = value;
    }

    /**
     * Gets the value of the crtOri property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCrtOri() {
        return crtOri;
    }

    /**
     * Sets the value of the crtOri property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCrtOri(JAXBElement<String> value) {
        this.crtOri = value;
    }

    /**
     * Gets the value of the crtState property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCrtState() {
        return crtState;
    }

    /**
     * Sets the value of the crtState property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCrtState(JAXBElement<String> value) {
        this.crtState = value;
    }

    /**
     * Gets the value of the crtTitle property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCrtTitle() {
        return crtTitle;
    }

    /**
     * Sets the value of the crtTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCrtTitle(JAXBElement<String> value) {
        this.crtTitle = value;
    }

    /**
     * Gets the value of the dbapp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDbapp() {
        return dbapp;
    }

    /**
     * Sets the value of the dbapp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDbapp(JAXBElement<String> value) {
        this.dbapp = value;
    }

}
