//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 07:26:16 PM CDT 
//


package svc.data.citations.datasources.regis.org.datacontract.schemas._2004._07.rejis_services_court;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FullCaseView complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FullCaseView"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AgcyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AgcyOri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AssdAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="BalDue" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="BondSetAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="CaseNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CaseStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CaseStatusDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ChrgCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ChrgDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CourtName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CourtWebSite" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DefAttyAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DefAttyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DefAttyPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeftAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeftName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DispDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="DispDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Dob" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="FilingDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="IssuingAgcy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="JudgeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NextDktCrtRm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NextDktDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="Ocn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OrigDktCrtRm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OrigDktDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="Plea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProbDays" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="ProbMonths" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="ProbYears" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="PymtUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SentExecCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SentExecDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StateChrg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Statute" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TktNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ViolAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ViolDttm" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="isAgcyPlus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FullCaseView", propOrder = {
    "agcyId",
    "agcyOri",
    "assdAmt",
    "balDue",
    "bondSetAmt",
    "caseNum",
    "caseStatus",
    "caseStatusDesc",
    "chrgCode",
    "chrgDesc",
    "courtName",
    "courtWebSite",
    "defAttyAddr",
    "defAttyName",
    "defAttyPhone",
    "deftAddr",
    "deftName",
    "dispDate",
    "dispDesc",
    "dob",
    "filingDate",
    "issuingAgcy",
    "judgeName",
    "lastName",
    "nextDktCrtRm",
    "nextDktDate",
    "ocn",
    "origDktCrtRm",
    "origDktDate",
    "plea",
    "probDays",
    "probMonths",
    "probYears",
    "pymtUrl",
    "sentExecCode",
    "sentExecDesc",
    "stateChrg",
    "statute",
    "tktNum",
    "violAddr",
    "violDttm",
    "isAgcyPlus"
})
public class FullCaseView {

    @XmlElementRef(name = "AgcyId", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> agcyId;
    @XmlElementRef(name = "AgcyOri", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> agcyOri;
    @XmlElementRef(name = "AssdAmt", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> assdAmt;
    @XmlElementRef(name = "BalDue", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> balDue;
    @XmlElementRef(name = "BondSetAmt", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> bondSetAmt;
    @XmlElementRef(name = "CaseNum", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> caseNum;
    @XmlElementRef(name = "CaseStatus", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> caseStatus;
    @XmlElementRef(name = "CaseStatusDesc", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> caseStatusDesc;
    @XmlElementRef(name = "ChrgCode", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> chrgCode;
    @XmlElementRef(name = "ChrgDesc", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> chrgDesc;
    @XmlElementRef(name = "CourtName", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> courtName;
    @XmlElementRef(name = "CourtWebSite", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> courtWebSite;
    @XmlElementRef(name = "DefAttyAddr", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> defAttyAddr;
    @XmlElementRef(name = "DefAttyName", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> defAttyName;
    @XmlElementRef(name = "DefAttyPhone", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> defAttyPhone;
    @XmlElementRef(name = "DeftAddr", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> deftAddr;
    @XmlElementRef(name = "DeftName", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> deftName;
    @XmlElement(name = "DispDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dispDate;
    @XmlElementRef(name = "DispDesc", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dispDesc;
    @XmlElement(name = "Dob")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dob;
    @XmlElement(name = "FilingDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar filingDate;
    @XmlElementRef(name = "IssuingAgcy", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> issuingAgcy;
    @XmlElementRef(name = "JudgeName", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> judgeName;
    @XmlElementRef(name = "LastName", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lastName;
    @XmlElementRef(name = "NextDktCrtRm", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> nextDktCrtRm;
    @XmlElement(name = "NextDktDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar nextDktDate;
    @XmlElementRef(name = "Ocn", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ocn;
    @XmlElementRef(name = "OrigDktCrtRm", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> origDktCrtRm;
    @XmlElement(name = "OrigDktDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar origDktDate;
    @XmlElementRef(name = "Plea", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> plea;
    @XmlElementRef(name = "ProbDays", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> probDays;
    @XmlElementRef(name = "ProbMonths", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> probMonths;
    @XmlElementRef(name = "ProbYears", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> probYears;
    @XmlElementRef(name = "PymtUrl", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> pymtUrl;
    @XmlElementRef(name = "SentExecCode", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> sentExecCode;
    @XmlElementRef(name = "SentExecDesc", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> sentExecDesc;
    @XmlElementRef(name = "StateChrg", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> stateChrg;
    @XmlElementRef(name = "Statute", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> statute;
    @XmlElementRef(name = "TktNum", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tktNum;
    @XmlElementRef(name = "ViolAddr", namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", type = JAXBElement.class, required = false)
    protected JAXBElement<String> violAddr;
    @XmlElement(name = "ViolDttm")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar violDttm;
    protected Boolean isAgcyPlus;

    /**
     * Gets the value of the agcyId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAgcyId() {
        return agcyId;
    }

    /**
     * Sets the value of the agcyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAgcyId(JAXBElement<String> value) {
        this.agcyId = value;
    }

    /**
     * Gets the value of the agcyOri property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAgcyOri() {
        return agcyOri;
    }

    /**
     * Sets the value of the agcyOri property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAgcyOri(JAXBElement<String> value) {
        this.agcyOri = value;
    }

    /**
     * Gets the value of the assdAmt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getAssdAmt() {
        return assdAmt;
    }

    /**
     * Sets the value of the assdAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setAssdAmt(JAXBElement<BigDecimal> value) {
        this.assdAmt = value;
    }

    /**
     * Gets the value of the balDue property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getBalDue() {
        return balDue;
    }

    /**
     * Sets the value of the balDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setBalDue(JAXBElement<BigDecimal> value) {
        this.balDue = value;
    }

    /**
     * Gets the value of the bondSetAmt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getBondSetAmt() {
        return bondSetAmt;
    }

    /**
     * Sets the value of the bondSetAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setBondSetAmt(JAXBElement<BigDecimal> value) {
        this.bondSetAmt = value;
    }

    /**
     * Gets the value of the caseNum property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCaseNum() {
        return caseNum;
    }

    /**
     * Sets the value of the caseNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCaseNum(JAXBElement<String> value) {
        this.caseNum = value;
    }

    /**
     * Gets the value of the caseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCaseStatus() {
        return caseStatus;
    }

    /**
     * Sets the value of the caseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCaseStatus(JAXBElement<String> value) {
        this.caseStatus = value;
    }

    /**
     * Gets the value of the caseStatusDesc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCaseStatusDesc() {
        return caseStatusDesc;
    }

    /**
     * Sets the value of the caseStatusDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCaseStatusDesc(JAXBElement<String> value) {
        this.caseStatusDesc = value;
    }

    /**
     * Gets the value of the chrgCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getChrgCode() {
        return chrgCode;
    }

    /**
     * Sets the value of the chrgCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setChrgCode(JAXBElement<String> value) {
        this.chrgCode = value;
    }

    /**
     * Gets the value of the chrgDesc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getChrgDesc() {
        return chrgDesc;
    }

    /**
     * Sets the value of the chrgDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setChrgDesc(JAXBElement<String> value) {
        this.chrgDesc = value;
    }

    /**
     * Gets the value of the courtName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCourtName() {
        return courtName;
    }

    /**
     * Sets the value of the courtName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCourtName(JAXBElement<String> value) {
        this.courtName = value;
    }

    /**
     * Gets the value of the courtWebSite property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCourtWebSite() {
        return courtWebSite;
    }

    /**
     * Sets the value of the courtWebSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCourtWebSite(JAXBElement<String> value) {
        this.courtWebSite = value;
    }

    /**
     * Gets the value of the defAttyAddr property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDefAttyAddr() {
        return defAttyAddr;
    }

    /**
     * Sets the value of the defAttyAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDefAttyAddr(JAXBElement<String> value) {
        this.defAttyAddr = value;
    }

    /**
     * Gets the value of the defAttyName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDefAttyName() {
        return defAttyName;
    }

    /**
     * Sets the value of the defAttyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDefAttyName(JAXBElement<String> value) {
        this.defAttyName = value;
    }

    /**
     * Gets the value of the defAttyPhone property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDefAttyPhone() {
        return defAttyPhone;
    }

    /**
     * Sets the value of the defAttyPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDefAttyPhone(JAXBElement<String> value) {
        this.defAttyPhone = value;
    }

    /**
     * Gets the value of the deftAddr property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDeftAddr() {
        return deftAddr;
    }

    /**
     * Sets the value of the deftAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDeftAddr(JAXBElement<String> value) {
        this.deftAddr = value;
    }

    /**
     * Gets the value of the deftName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDeftName() {
        return deftName;
    }

    /**
     * Sets the value of the deftName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDeftName(JAXBElement<String> value) {
        this.deftName = value;
    }

    /**
     * Gets the value of the dispDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDispDate() {
        return dispDate;
    }

    /**
     * Sets the value of the dispDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDispDate(XMLGregorianCalendar value) {
        this.dispDate = value;
    }

    /**
     * Gets the value of the dispDesc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDispDesc() {
        return dispDesc;
    }

    /**
     * Sets the value of the dispDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDispDesc(JAXBElement<String> value) {
        this.dispDesc = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDob() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDob(XMLGregorianCalendar value) {
        this.dob = value;
    }

    /**
     * Gets the value of the filingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFilingDate() {
        return filingDate;
    }

    /**
     * Sets the value of the filingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFilingDate(XMLGregorianCalendar value) {
        this.filingDate = value;
    }

    /**
     * Gets the value of the issuingAgcy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIssuingAgcy() {
        return issuingAgcy;
    }

    /**
     * Sets the value of the issuingAgcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIssuingAgcy(JAXBElement<String> value) {
        this.issuingAgcy = value;
    }

    /**
     * Gets the value of the judgeName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getJudgeName() {
        return judgeName;
    }

    /**
     * Sets the value of the judgeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setJudgeName(JAXBElement<String> value) {
        this.judgeName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLastName(JAXBElement<String> value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the nextDktCrtRm property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNextDktCrtRm() {
        return nextDktCrtRm;
    }

    /**
     * Sets the value of the nextDktCrtRm property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNextDktCrtRm(JAXBElement<String> value) {
        this.nextDktCrtRm = value;
    }

    /**
     * Gets the value of the nextDktDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNextDktDate() {
        return nextDktDate;
    }

    /**
     * Sets the value of the nextDktDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNextDktDate(XMLGregorianCalendar value) {
        this.nextDktDate = value;
    }

    /**
     * Gets the value of the ocn property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOcn() {
        return ocn;
    }

    /**
     * Sets the value of the ocn property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOcn(JAXBElement<String> value) {
        this.ocn = value;
    }

    /**
     * Gets the value of the origDktCrtRm property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOrigDktCrtRm() {
        return origDktCrtRm;
    }

    /**
     * Sets the value of the origDktCrtRm property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOrigDktCrtRm(JAXBElement<String> value) {
        this.origDktCrtRm = value;
    }

    /**
     * Gets the value of the origDktDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOrigDktDate() {
        return origDktDate;
    }

    /**
     * Sets the value of the origDktDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrigDktDate(XMLGregorianCalendar value) {
        this.origDktDate = value;
    }

    /**
     * Gets the value of the plea property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPlea() {
        return plea;
    }

    /**
     * Sets the value of the plea property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPlea(JAXBElement<String> value) {
        this.plea = value;
    }

    /**
     * Gets the value of the probDays property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getProbDays() {
        return probDays;
    }

    /**
     * Sets the value of the probDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setProbDays(JAXBElement<Integer> value) {
        this.probDays = value;
    }

    /**
     * Gets the value of the probMonths property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getProbMonths() {
        return probMonths;
    }

    /**
     * Sets the value of the probMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setProbMonths(JAXBElement<Integer> value) {
        this.probMonths = value;
    }

    /**
     * Gets the value of the probYears property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getProbYears() {
        return probYears;
    }

    /**
     * Sets the value of the probYears property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setProbYears(JAXBElement<Integer> value) {
        this.probYears = value;
    }

    /**
     * Gets the value of the pymtUrl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPymtUrl() {
        return pymtUrl;
    }

    /**
     * Sets the value of the pymtUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPymtUrl(JAXBElement<String> value) {
        this.pymtUrl = value;
    }

    /**
     * Gets the value of the sentExecCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSentExecCode() {
        return sentExecCode;
    }

    /**
     * Sets the value of the sentExecCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSentExecCode(JAXBElement<String> value) {
        this.sentExecCode = value;
    }

    /**
     * Gets the value of the sentExecDesc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSentExecDesc() {
        return sentExecDesc;
    }

    /**
     * Sets the value of the sentExecDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSentExecDesc(JAXBElement<String> value) {
        this.sentExecDesc = value;
    }

    /**
     * Gets the value of the stateChrg property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStateChrg() {
        return stateChrg;
    }

    /**
     * Sets the value of the stateChrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStateChrg(JAXBElement<String> value) {
        this.stateChrg = value;
    }

    /**
     * Gets the value of the statute property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStatute() {
        return statute;
    }

    /**
     * Sets the value of the statute property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStatute(JAXBElement<String> value) {
        this.statute = value;
    }

    /**
     * Gets the value of the tktNum property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTktNum() {
        return tktNum;
    }

    /**
     * Sets the value of the tktNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTktNum(JAXBElement<String> value) {
        this.tktNum = value;
    }

    /**
     * Gets the value of the violAddr property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getViolAddr() {
        return violAddr;
    }

    /**
     * Sets the value of the violAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setViolAddr(JAXBElement<String> value) {
        this.violAddr = value;
    }

    /**
     * Gets the value of the violDttm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getViolDttm() {
        return violDttm;
    }

    /**
     * Sets the value of the violDttm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setViolDttm(XMLGregorianCalendar value) {
        this.violDttm = value;
    }

    /**
     * Gets the value of the isAgcyPlus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAgcyPlus() {
        return isAgcyPlus;
    }

    /**
     * Sets the value of the isAgcyPlus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAgcyPlus(Boolean value) {
        this.isAgcyPlus = value;
    }

}
