//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 07:26:16 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.datacontract.org/2004/07/REJIS.Services.Court.MuniCourt", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package svc.data.citations.datasources.regis.org.datacontract.schemas._2004._07.rejis_services_court;
